///@description KSW - Set Series

function scr_KSW_SetSeries()
{
	#region Setup
	global.KSW_SeriesCount = 0;
	
	global.KSW_SeriesList = [];
	global.KSW_SeriesIDs = ds_map_create();
	#endregion
	
	#region Add Series Here
	scr_KSW_AddSeries("kirby","Kirby");
	scr_KSW_AddSeries("castlevania","Castlevania");
	scr_KSW_AddSeries("metroid","Metroid");
	scr_KSW_AddSeries("metroidPrimeOrigins","Metroid Prime Origins");
	scr_KSW_AddSeries("insaniquarium","Insaniquarium");
	scr_KSW_AddSeries("slayersX","Slayers X");
	scr_KSW_AddSeries("superMario","Super Mario");
	scr_KSW_AddSeries("sonicTheHedgehog","Sonic The Hedgehog");
	scr_KSW_AddSeries("doshinTheGiant","Doshin The Giant");
	scr_KSW_AddSeries("theLegendOfZelda","The Legend of Zelda");
	scr_KSW_AddSeries("terraria","Terraria");
	scr_KSW_AddSeries("terrariaCalamity","Terraria: Calamity Mod");
	scr_KSW_AddSeries("pokemon","Pokemon");
	scr_KSW_AddSeries("pmdEoF","PMD: Explorers of Fortune");
	scr_KSW_AddSeries("warioLand","Wario Land");
	scr_KSW_AddSeries("yugioh","Yu-Gi-Oh");
	scr_KSW_AddSeries("godzilla","Godzilla");
	scr_KSW_AddSeries("monsterHunter","Monster Hunter");
	scr_KSW_AddSeries("pikmin","Pikmin");
	scr_KSW_AddSeries("deirdre","Deirdre");
	scr_KSW_AddSeries("spongebob","Spongebob");
	scr_KSW_AddSeries("caveStory","Cave Story");
	scr_KSW_AddSeries("minecraft","Minecraft");
	scr_KSW_AddSeries("plantsVsZombies","Plants vs Zombies");
	scr_KSW_AddSeries("doom","DOOM");
	scr_KSW_AddSeries("theBindingOfIsaacRebirth","The Binding of Isaac: Rebirth");
	scr_KSW_AddSeries("theBindingOfIsaacForgottenFables","The Binding of Isaac - Forgotten Fables");
	scr_KSW_AddSeries("kirbysDreamLand23","Kirby's Dream Land 2 + 3");
	scr_KSW_AddSeries("undertale","Undertale");
	scr_KSW_AddSeries("deltarune","Deltarune");
	scr_KSW_AddSeries("off","OFF");
	scr_KSW_AddSeries("donkeyKongCountry","Donkey Kong Country");
	scr_KSW_AddSeries("donkeyKongLandRemake","Donkey Kong Land: Remake");
	scr_KSW_AddSeries("digimon","Digimon");
	scr_KSW_AddSeries("hollowKnight","Hollow Knight");
	scr_KSW_AddSeries("saintsRow","Saints Row");
	scr_KSW_AddSeries("darius","Darius");
	scr_KSW_AddSeries("starfy","Starfy");
	scr_KSW_AddSeries("crashBandicoot","Crash Bandicoot");
	scr_KSW_AddSeries("yoshisIsland","Yoshi's Island");
	scr_KSW_AddSeries("balloonFight","Balloon Fight");
	scr_KSW_AddSeries("finalFantasy","Final Fantasy");
	scr_KSW_AddSeries("pizzaTower","Pizza Tower");
	scr_KSW_AddSeries("shovelKnight","Shovel Knight");
	scr_KSW_AddSeries("megaMan","Mega Man");
	scr_KSW_AddSeries("megaManSequelWars","Mega Man: The Sequel Wars");
	scr_KSW_AddSeries("peggle","Peggle");
	scr_KSW_AddSeries("antonBlast","AntonBlast");
	scr_KSW_AddSeries("dragonQuest","Dragon Quest");
	scr_KSW_AddSeries("astroBot","Astro Bot");
	scr_KSW_AddSeries("angryBirds","Angry Birds");
	scr_KSW_AddSeries("bejewelled","Bejewelled");
	scr_KSW_AddSeries("pacMan","Pac-Man");
	scr_KSW_AddSeries("superSmashBros","Super Smash Bros");
	scr_KSW_AddSeries("rayman","Rayman");
	scr_KSW_AddSeries("spaceInvaders","Space Invaders");
	scr_KSW_AddSeries("amongUs","Among Us");
	scr_KSW_AddSeries("katatsumuri","Katatsumuri");
	scr_KSW_AddSeries("animalCrossing","Animal Crossing");
	scr_KSW_AddSeries("helloKitty","Hello Kitty");
	scr_KSW_AddSeries("happyAppy","Happy Appy");
	scr_KSW_AddSeries("stardewValley","Stardew Valley");
	scr_KSW_AddSeries("starbound","Starbound");
	scr_KSW_AddSeries("webfishing","Webfishing");
	scr_KSW_AddSeries("coreKeeper","Core Keeper");
	scr_KSW_AddSeries("waddleDevVsKirbyDarkDawn","Waddle Dev vs Kirby Dark Dawn");
	scr_KSW_AddSeries("mrMix","Mr. Mix");
	scr_KSW_AddSeries("rubato","RUBATO");
	scr_KSW_AddSeries("gundam","Mobile Suit Gundam");
	scr_KSW_AddSeries("wildWoody","Wild Woody");
	scr_KSW_AddSeries("wiiPlay","Wii Play");
	scr_KSW_AddSeries("ultraman","Ultraman");
	scr_KSW_AddSeries("fossilFighters","Fossil Fighters");
	scr_KSW_AddSeries("medabots","Medabots");
	scr_KSW_AddSeries("octopathtraveler","Octopath Traveler");
	scr_KSW_AddSeries("rogueHeroes","Rogue Heroes: Ruins of Tasos");
	scr_KSW_AddSeries("flappyBird","Flappy Bird");
	scr_KSW_AddSeries("scribblenauts","Scribblenauts");
	scr_KSW_AddSeries("nuclearThrone","Nuclear Throne");
	scr_KSW_AddSeries("fiveNightsAtFreddys","Five Nights at Freddy's");
	scr_KSW_AddSeries("snowBros","Snow Bros");
	scr_KSW_AddSeries("clashClans","Clash of Clans");
	scr_KSW_AddSeries("celeste","Celeste");
	scr_KSW_AddSeries("touhouProject","Touhou Project");
	scr_KSW_AddSeries("umamusume","Umamusume");
	scr_KSW_AddSeries("megaManUnlimited","Mega Man Unlimited");
	scr_KSW_AddSeries("bloodstained","Bloodstained");
	scr_KSW_AddSeries("misc","Misc");
	scr_KSW_AddSeries("undertaleYellow","Undertale Yellow");
	scr_KSW_AddSeries("DaveTheDiver","Dave the Diver");
	scr_KSW_AddSeries("KeroBlaster","Kero Blaster");
	scr_KSW_AddSeries("deltarot","Deltarot");
	scr_KSW_AddSeries("jamesPond","James Pond");
	scr_KSW_AddSeries("startropics","StarTropics");
	scr_KSW_AddSeries("earthwormJim","Earthworm Jim");
	scr_KSW_AddSeries("worms","Worms");
	scr_KSW_AddSeries("alienSoldier","Alien Soldier");
	scr_KSW_AddSeries("jurassicPark","Jurassic Park");
	scr_KSW_AddSeries("buckyOHare","Bucky O'Hare");
	scr_KSW_AddSeries("eccoTheDolphin","Ecco the Dolphin");
	scr_KSW_AddSeries("liveALive","Live A Live");
	scr_KSW_AddSeries("enterTheGungeon","Enter The Gungeon");
	scr_KSW_AddSeries("fortnite","Fortnite");
	scr_KSW_AddSeries("fieldsOfMistria","Fields of Mistria");
	scr_KSW_AddSeries("sh2Demake","Silent Hill 2 Demake");
	scr_KSW_AddSeries("rhythmHeaven","Rhythm Heaven");
	scr_KSW_AddSeries("bioshock","Bioshock");
	scr_KSW_AddSeries("residentEvil","Resident Evil");
	scr_KSW_AddSeries("ghoulsNGhosts","Ghouls 'n Ghosts");
	scr_KSW_AddSeries("mother","Mother");
	scr_KSW_AddSeries("motherEncore","Mother: Encore");
	scr_KSW_AddSeries("banjo","Banjo-Kazooie");
	scr_KSW_AddSeries("haloDemake","Halo Combat Devolved");
	scr_KSW_AddSeries("angryBirds","Angry Birds");
	scr_KSW_AddSeries("geometryDash","Geometry Dash");
	scr_KSW_AddSeries("metalGear","MetalGearSolid");
	scr_KSW_AddSeries("fallout","Fallout");
	scr_KSW_AddSeries("portal","Portal");
	scr_KSW_AddSeries("kirbySoftnWet","Kirby ~ Soft & Wet");
	scr_KSW_AddSeries("metaKnightmareStellar","Meta Knightmare Stellar Symphony");
	scr_KSW_AddSeries("kirbyGambleGalaxyStories","Kirby ~ Beyond the Violet Night");
	scr_KSW_AddSeries("minatheHollower","Mina The Hollower");
	scr_KSW_AddSeries("nightmareCollection","Nightmare Collection");
	scr_KSW_AddSeries("dreamLandEXE","Dreamland.EXE");
	scr_KSW_AddSeries("kirbyEXE","Kirby EXE");
	scr_KSW_AddSeries("dreamLand2002","Dream Land 2002");
	scr_KSW_AddSeries("bendyAndTheInkMachine","Bendy and the Ink Machine");
	scr_KSW_AddSeries("shinMegamiTensei","Shin Megami Tensei");
	scr_KSW_AddSeries("minatheHollower","Mina The Hollower")
	scr_KSW_AddSeries("iB","IB");
	scr_KSW_AddSeries("aHatInTime","A Hat In Time");
	scr_KSW_AddSeries("omori","Omori");
	scr_KSW_AddSeries("LookOutside","Look Outside");
	scr_KSW_AddSeries("theBattleCats","The Battle Cats");
	scr_KSW_AddSeries("CassetteBeasts","Cassette Beasts");
	scr_KSW_AddSeries("riskRain","Risk of Rain");
	scr_KSW_AddSeries("fish","FISH");
	scr_KSW_AddSeries("bomberman","Bomberman");
	scr_KSW_AddSeries("persona","Persona");
	scr_KSW_AddSeries("vampireSurvivors","Vampire Survivors");
	scr_KSW_AddSeries("kidKirby","Kid Kirby Recreation");
	#endregion
}